use Planes_De_Estudio
go

UPDATE MATERIA 
SET NOMBREM = 'Sistemas inteligentes'
WHERE IDMATERIA = 'MAT34'
go

UPDATE MAESTROS 
SET NOMBREP = 'CEJUDO LAURA'
WHERE IDMAESTRO = 'AAA24'
go

UPDATE ALUMNO
SET NOMBREA = 'SANCHEZ MINERDINO'
WHERE IDALUMNO = '410000036'
go

DELETE FROM CURSA WHERE CALIFICACION = 6
go

DELETE FROM IMPARTE WHERE IDMAESTRO ='AAA27'
go

DELETE FROM INCLUYE WHERE SEMESTRE = 8
go