use Planes_De_Estudio
go

select NOMBREP, NOMBREM, NOMBREA
from   ALUMNO, MATERIA, MAESTROS, CURSA, IMPARTE
where  ALUMNO.IDALUMNO = CURSA.IDALUMNO
  AND  CURSA.IDMATERIA = MATERIA.IDMATERIA
  AND  CURSA.IDMATERIA = IMPARTE.IDMATERIA
  AND  MAESTROS.IDMAESTRO = IMPARTE.IDMAESTRO
go
