use Planes_De_Estudio
go

CREATE TRIGGER DELMATERIA
ON MATERIA
FOR DELETE AS
BEGIN
DELETE IMPARTE
FROM IMPARTE, deleted
WHERE IMPARTE.IDMATERIA = deleted.IDMATERIA

DELETE CURSA
FROM CURSA, deleted
WHERE CURSA.IDMATERIA = deleted.IDMATERIA

DELETE INCLUYE
FROM INCLUYE, deleted
WHERE INCLUYE.IDMATERIA = deleted.IDMATERIA
END
GO

CREATE TRIGGER DELMAESTROS
ON MAESTROS
FOR DELETE AS
BEGIN
DELETE IMPARTE
FROM IMPARTE, deleted
WHERE IMPARTE.IDMAESTRO = deleted.IDMAESTRO
END
GO

CREATE TRIGGER DELALUMNO
ON ALUMNO
FOR DELETE AS
BEGIN
DELETE CURSA
FROM CURSA, deleted
WHERE CURSA.IDALUMNO = deleted.IDALUMNO
END
GO

CREATE TRIGGER DELCARRERA
ON CARRERA
FOR DELETE AS
BEGIN
DELETE INCLUYE
FROM INCLUYE, deleted
WHERE INCLUYE.IDCARRERA = deleted.IDCARRERA

UPDATE ALUMNO
SET IDCARRERA=NULL 
FROM  ALUMNO, deleted
WHERE ALUMNO.IDCARRERA = deleted.IDCARRERA
END
GO

/*UPDATES*/

CREATE TRIGGER UPDMATERIA
ON MATERIA
FOR UPDATE AS

IF UPDATE(IDMATERIA)
BEGIN
UPDATE IMPARTE
SET IDMATERIA = inserted.IDMATERIA 
FROM IMPARTE, deleted, inserted
WHERE deleted.IDMATERIA = IMPARTE.IDMATERIA
UPDATE INCLUYE
SET IDMATERIA = inserted.IDMATERIA 
FROM INCLUYE, deleted, inserted
WHERE deleted.IDMATERIA = INCLUYE.IDMATERIA
END
GO

CREATE TRIGGER UPDMAESTROS
ON MAESTROS
FOR UPDATE AS

IF UPDATE(IDMAESTRO)
BEGIN
UPDATE IMPARTE
SET IDMAESTRO = inserted.IDMAESTRO 
FROM IMPARTE, deleted, inserted
WHERE deleted.IDMAESTRO = IMPARTE.IDMAESTRO
END
GO

CREATE TRIGGER UPDALUMNO
ON ALUMNO
FOR UPDATE AS

IF UPDATE(IDALUMNO)
BEGIN
UPDATE CURSA
SET IDALUMNO = inserted.IDALUMNO 
FROM CURSA, deleted, inserted
WHERE deleted.IDALUMNO = CURSA.IDALUMNO
END
GO

CREATE TRIGGER UPDCARRERA
ON CARRERA
FOR UPDATE AS

IF UPDATE(IDCARRERA)
BEGIN
UPDATE INCLUYE
SET IDCARRERA = inserted.IDCARRERA
FROM INCLUYE, deleted, inserted
WHERE deleted.IDCARRERA = INCLUYE.IDCARRERA
UPDATE ALUMNO
SET IDCARRERA = inserted.IDCARRERA
FROM ALUMNO, deleted, inserted
WHERE deleted.IDCARRERA = ALUMNO.IDCARRERA
END
GO
